-- DateGenie 이메일 인증 시스템 데이터베이스 설정
-- 이 스크립트를 Oracle 데이터베이스에서 실행하세요

-- 1. USER_EMAIL_AUTH 테이블 생성
CREATE TABLE CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL,
    VERIFICATION_TOKEN VARCHAR2(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL,
    VERIFIED NUMBER(1,0) DEFAULT 0
);

-- 2. 시퀀스 생성 (ID 자동 생성용)
CREATE SEQUENCE CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999999
    MINVALUE 1
    CACHE 20
    NOORDER
    NOCYCLE;

-- 3. 성능 향상을 위한 인덱스 생성
-- 이메일로 빠른 조회를 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_USER_EMAIL_AUTH_EMAIL 
    ON CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (EMAIL);

-- 토큰으로 빠른 조회를 위한 유니크 인덱스
CREATE UNIQUE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_USER_EMAIL_AUTH_TOKEN 
    ON CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (VERIFICATION_TOKEN);

-- 만료 시간으로 정리 작업을 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_USER_EMAIL_AUTH_EXPIRES 
    ON CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (EXPIRES_AT);

-- 인증 상태로 조회를 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_USER_EMAIL_AUTH_VERIFIED 
    ON CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (VERIFIED);

-- 복합 인덱스: 이메일과 인증상태로 조회
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_USER_EMAIL_AUTH_EMAIL_VERIFIED 
    ON CAMPUS_24IS_CLOUD3_P2_4.USER_EMAIL_AUTH (EMAIL, VERIFIED);

-- 4. 테이블 및 시퀀스 생성 확인
SELECT 'USER_EMAIL_AUTH 테이블 생성 완료' FROM DUAL;
SELECT 'USER_EMAIL_AUTH_SEQ 시퀀스 생성 완료' FROM DUAL;

-- 5. 생성된 객체 확인 쿼리
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = 'USER_EMAIL_AUTH';
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'USER_EMAIL_AUTH_SEQ';