-- DateGenie 이메일 인증 시스템 데이터베이스 설정
-- Oracle Database용 시퀀스 및 인덱스 생성 스크립트

-- 1. EMAIL_VERIFICATION 테이블의 ID 컬럼용 시퀀스 생성
CREATE SEQUENCE CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999999
    MINVALUE 1
    CACHE 20
    NOORDER
    NOCYCLE;

-- 2. 성능 향상을 위한 인덱스 생성
-- 이메일로 빠른 조회를 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_EMAIL_VERIFICATION_EMAIL 
    ON CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION (EMAIL);

-- 토큰으로 빠른 조회를 위한 인덱스 (유니크 인덱스)
CREATE UNIQUE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_EMAIL_VERIFICATION_TOKEN 
    ON CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION (VERIFICATION_TOKEN);

-- 만료 시간으로 정리 작업을 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_EMAIL_VERIFICATION_EXPIRES 
    ON CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION (EXPIRES_AT);

-- 인증 상태로 조회를 위한 인덱스
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_EMAIL_VERIFICATION_VERIFIED 
    ON CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION (VERIFIED);

-- 복합 인덱스: 이메일과 인증상태로 조회
CREATE INDEX CAMPUS_24IS_CLOUD3_P2_4.IDX_EMAIL_VERIFICATION_EMAIL_VERIFIED 
    ON CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION (EMAIL, VERIFIED);

-- 3. 시퀀스와 인덱스 정보 확인 쿼리 (실행 후 확인용)
/*
-- 시퀀스 확인
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE 
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME = 'EMAIL_VERIFICATION_SEQ';

-- 인덱스 확인
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES 
WHERE TABLE_NAME = 'EMAIL_VERIFICATION';

-- 인덱스 컬럼 확인
SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME = 'EMAIL_VERIFICATION'
ORDER BY INDEX_NAME, COLUMN_POSITION;
*/

-- 4. 테스트 데이터 (개발/테스트 환경에서만 사용)
/*
-- 테스트용 이메일 인증 데이터 삽입 예시
INSERT INTO CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION 
(ID, EMAIL, VERIFICATION_TOKEN, CREATED_AT, EXPIRES_AT, VERIFIED) 
VALUES (
    CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION_SEQ.NEXTVAL,
    'test@example.com',
    'test_token_123',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '24' HOUR,
    0
);

-- 테스트 데이터 조회
SELECT * FROM CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION WHERE EMAIL = 'test@example.com';

-- 테스트 데이터 삭제
DELETE FROM CAMPUS_24IS_CLOUD3_P2_4.EMAIL_VERIFICATION WHERE EMAIL = 'test@example.com';
*/